fail_fast: true
repos:
  - repo: local
    hooks:
      - id: biome
        name: Biome
        entry: docker compose run -T --rm worker npm run biome-lint
        language: system
        always_run: true
        pass_filenames: false
      - id: vitest
        name: Vitest
        entry: docker compose run -T --rm worker npm run test
        language: system
        always_run: true
        pass_filenames: false
